---
title: "Literature Review"
author: "Michael Fehl"
date: 02-01-2026
tbl-colwidths: [75,25]
format:
  html:
    embed-resources: true
---

For our research project into remittances from Mexican migrants working in the US, it is important to understand the current state of the research. We are then able to get a clearer picture regarding what has been done, weaknesses/strengths in the research, gaps we could potentially fill in, etc. We can divide up the literature review into different categories to organize our readings a bit better.

::: {.column-page}

::: {#tbl-panel layout-ncol=2 layout-nrow=2}

| Paper | Link |
|------|------|
| Caballero, Cadena, & Kovak (2023) “The International Transmission of Local Economic Shocks through Migrant Networks”    |  [Paper](https://www.colorado.edu/faculty/cadena/media/7)    |
| Kagin, Justin, & Charlton (2014) ”International Migration, Remittances, and the Impacts of the Great Recession in Rural Mexico”    |  [Paper](https://academic.oup.com/book/3872/chapter-abstract/145405667?redirectedFrom=fulltext&login=true)    |
| Bettin, Presbitero, & Spatafora (2014) "Remittances and Vulnerability in Developing Countries" | [Paper](https://www.imf.org/en/-/media/websites/imf/imported-full-text-pdf/external/pubs/ft/wp/2014/_wp1413.pdf) |
| Yang (2008): ”International Migration, Remittances, and Household Investment: Evidence From Philippine Migrants’ Exchange Rate Shocks”   |  [Paper](https://www.nber.org/system/files/working_papers/w12325/w12325.pdf)    |

: Remittances {#tbl-first}

| Paper | Link |
|------|------|
| Bazzi, Gaduh, Rothenberg, & Wong (2016) "Skill Transferability, Migration, and Development: Evidence from Population Resettlement in Indonesia."    |  [Paper](https://www.stern.nyu.edu/sites/default/files/assets/documents/Skill%20Transferability%2C%20Migration%2C%20and%20Development.pdf) |
|Caballero, Cadena, & Kovak (2018) “Measuring Geographic Migration Patterns using Matrículas Consulares” |  [Paper](https://pmc.ncbi.nlm.nih.gov/articles/PMC6680024/)    |
| Massey & Zenteno (1999) ”The Dynamics of Mass Migration”    | [Paper](https://www.jstor.org/stable/47395)|
| Ward (2020) "The Not-So-Hot Melting Pot: The Persistence of Outcomes for Descendants of the Age of Mass Migration" | [Paper](https://pubs.aeaweb.org/doi/pdfplus/10.1257/app.20170382)

: Migration {#tbl-second}

| Paper | Link |
|------|------|
| Amuedo-Dorantes & Pozo (2006) ”Remittances as insurance: evidence from Mexican immigrants”    |  [Paper](https://www.jstor.org/stable/20008008?seq=1)    |
| Lucas & Stark (1985) ”Motivation to Remit: Evidence from Botswana    |  [Paper](https://www.jstor.org/stable/1833062?seq=2)    |
| Agarwal & Horowitz (2002): ”Are International Remittances Altruism or Insurance? Evidence from Guyana”    |  [Paper](https://www.sciencedirect.com/science/article/abs/pii/S0305750X02001183)    |

: Motivation {#tbl-third}

| Paper | Link |
|------|------|
| Albert & Monras (2022) ”Immigration and Spatial Equilibrium: The Role of Expenditures in the Country of Origin”   |  [Paper](https://crei.cat/wp-content/uploads/2022/04/ISE.pdf)    |
| Redding & Rossi-Hansberg (2017) ”Quantitative Spatial Economics”    |  [Paper](https://www.princeton.edu/~erossi/QSE.pdf)    |
| Munshi (2003): ”Networks in the Modern Economy: Mexican Migrants in the U. S. Labor Market”  | [Paper](https://inequality.stanford.edu/sites/default/files/media/_media/pdf/Reference%20Media/Munshi_2003_Social%20Networks.pdf)|

: Networks & Spatial Models {#tbl-fourth}

Literature Review Organization
:::

:::

Below is a summary of each paper, noting the most important and/or relevant results from it.

## Remittances

*Papers found in* @tbl-first

### Cabarello et Al. (2023)



### Kagin et Al. (2014)



### Bettin et Al. (2014)



### Yang (2008)



## Migration

*Papers found in* @tbl-second

### Cabarello et Al. (2018)

Evaluates data validity from MCAS program. 

Common issues are that: (1) most data between migration patterns, either the data is too zoomed out and aggregated (MX Census, ACS) do not report flows between individuals from both countries, only sub-national geography data for their respective countries; for other nations, the information remains at a national level, no finer. (2) data that is zoomed in and very detailed regarding migration experiences (MMP), but comes with a very small sample size (1% of MX pop). MCAS data bridges the gap between these two issues: MCAS provides data at a ‘municipo’ level, rather than ‘state’ level, which has comparable differences in their measurements (state level avg destination has higher measurement error). Important for analysis.

Furthermore, they aim to resolve concerns regarding the data validity, since the MCAS program data is collected via voluntary action; however, they intend to resolve this doubt by showing that the data strongly matches with ‘standard,’ well-established data sources (MX, US household surveys).

References to other studies regarding previous migration increases probability of migration by lowering the costs, also affecting investment in origin communities, the set of individuals choosing to migrate, and approach to border-crossing. I believe they reference Garip (2016) as a summary to most of these empirical findings. 

Final aim is to show that MCAS data used in conjunction with household survey data to investigate MX-US migration research questions. They demonstrate this by using the LAWA to map effects of policy in Arizona back to specific migration origin communities.

Background on the MCAS: document provided by MX govt to citizens abroad int heir country of residence. Primarily used for returning to MX, opening bank accounts, loans, etc. Lots of benefits that would incentivize immigrants, even those undocumented; this is useful in tracking migration patterns for both documented AND undocumented immigrants, which typically are not accounted for in large-scale census survey data. Each MCAS includes an individual municipios (county) of birth, and US location where the card was issued. Over 2000 municipios and 75 US locations were represented.
7 million cards issued during 2006-2013 period. Valid for 5 years. All cards issued between 2006-2010 and still valid during at least a portion of 2011. They compare the number of valid cards in 2011-2013 to the estimated MX-born population of the US and estimates of unauthorized MX-born pop in the US, which they find 38% hold a MCAS. According to Masset et al. (2010), it is a reasonable assumption that (all)/(the majority) of MCAS holders are undocumented immigrants, as with legal status they would have no need for such additional documentation.

Proceed to compare migration patterns from MCAS to high-quality household surveys from MX and USA; from which, they compared the marginal distributions. Results show a very strong agreement between ACS and MCAS data regarding distribution of MX across US states, using a ln scale to account for heteroskedastic distribution across US states. Then compares MCAS to MX census data, with again there is a strong agreement in regards to distribution of MX source states traveling to the US. Municipio analysis is a bit noisier, yet still shows a very apparent relationship, which is quite rare at such a granular level and validates the data quality as being the same as ACS / Census in its accuracy.

Compares MCAS to ENADID, which reports migrants' state of residence in the US and their source location. Similar questions to MX census, the measure performs reasonably well, but not as good as ACS comparison; likely due to missing data in ENADID (only 41 states reports) – further, agreement between large states (TX, California) but more disagreement for mid-population states. The large differences from the ACS were only observed for the small states that ENADID omits; i.e., issue of a much smaller sample size; big advantage that the MCAS offers is a large sample size. “ENADID does not observe a sufficient number of migrants to credibly estimate source-specific destination distributions for the majority of Mexican sources.”

Use a dissimilarity index to measure difference in destination distribution between individuals from source ‘s” and from a reference group. 0 – identical dist (), 1 – no overlap (). E.g. if delta_s  = 0.21, 21% of the migrants from CdM, say, would need to relocate within the US to match the overall distribution of MX migrants’ chosen destinations (the national average distribution in a state). More discussion about source state and connection to certain states, how your state of origin is not a good proxy for destination settlement patterns; a strength of the MCAS data is the granularity of the data – these settlement patterns seem to operate more accurately at a municipo level. Example given: two municipos both in Michoacan: Ciudad Hidalgo & Tiquicheo. CH migrants primarily reside in Illinois (Chicago), whilst TQ migrants primarily reside in Texas. 

Examines this MCAS data with an example of policy being implemented in Arizona in Jan 2008 that led to a decline in the undocumented migrant population in AZ. Assumed that the policy’s effect on the labor market in the US for the average migrant from region ‘s’ is proportional to the share of MCAS card holders from the same region ‘s’ who lived in AZ in 2006. By looking at the log change in return migration (y_source,2010 - y_source,2005) using a linear reg with the sole regressor being the share of migrants from source ‘s’ selecting AZ as residence in 2006, before the policy LAWA was passed. Use states or municipos as source regions, treating states as indep obs, clustered at the state level when using municipos. 

State level: They found that return migration rates rose more in sending states with stronger network connections to AZ. E.g. Sonora saw a 30% increase in growth in its return migration in comparison to a state with no connection to AZ.Results weighted by 2000 MX population. Large SEs when reducing impact of high-leverage outliers indicates that state-level results on highly dependent on inclusion of a single high-leverage observation (e.g. Sonora).

Municipo level: similar estimates for change in log migration return rats at municipo level. SEs here are notably smaller, with no clear outliers driving the results; even when accounting for possible effects, SEs barely change, indicating a robustness at the granular data only available in the MCAS dataset. Further advantage is the ability to control for other changes over time that affect return migration rates – i.e., conditions changing in MX-state level may be correlated with a location’s connection to AZ, making it difficult to separate a causal relationship from the regression. Controlled using MX-state fixed-effects, removing any influence changing conditions in sending area had on migration rates. E.g. controlling for changes in state-level labor market conditions and changes in state-level crime. 

Same results when looking at emigration to US; dropped, big outlier by Sonora, robust at municipo level. 


### Bazzi et Al. (2016)



### Massey & Zenteno (1999)



### Ward (2020) 



## Motivation

*Papers found in* @tbl-third

### Amuedo-Dorantes & Pozo (2006)



### Lucas & Stark (1985)



### Agarwal & Horowitz (2002)



## Networks & Spatial Models

*Papers found in* @tbl-fourth

### Albert & Monras (2022)



### Redding & Rossi-Hansberg (2017)



### Munshi (2003)



